#!/bin/bash

function composekafka()
{
    read -p "input your ip address want to setup : " where
    
    #parse ip address
    if [ $where == "" ]; then
      read -p "null input your address : " where
    fi
    if [[ $where =~ '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' ]]; then
      read -p "not available input your address : " where
    fi

    where=$(curl ifconfig.me)
    echo "$where"
    SETUP_KAFKA_IP='s/EXTERNAL_IP/'$where'/g'

    #setup kafka address
    sudo sed -i $SETUP_KAFKA_IP ./docker-kafka/docker-compose.yml;

    echo "##########################################################"
    echo "#########       compose up kafka               ###########"
    echo "##########################################################"

    cd ./docker-kafka;
    sudo docker-compose up -d;

    cd ../;
    SETUP_ELK_IP='s/SETUP_LOG_IP/'$where'/g'
    sudo sed -i $SETUP_ELK_IP ./elk-docker/logstash/pipeline/logstash.conf;
    echo "vm.max_map_count=262144" >> /etc/sysctl.conf
    sudo sysctl -p
    echo "##########################################################"
    echo "#########       compose up elk stack           ###########"
    echo "##########################################################"
    cd ./elk-docker
    sudo docker-compose up -d;

}


# installdocker;
composekafka;
